version: "3.9"

services:
  backend:
    build: .
    container_name: backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./core:/app
      - ./media:/app/media
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=True
      - POSTGRES_DB=island_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root1234
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
    networks:
      - cloud-network

  db:
    image: postgres:16.4-bookworm
    container_name: postgres-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root1234
      POSTGRES_DB: island_db
    volumes:
      - postgres_data_fresh:/var/lib/postgresql/data
    networks:
      - cloud-network

volumes:
  postgres_data_fresh:

networks:
  cloud-network:
    driver: bridge

